# MkDocs configuration for Percona website builds

site_name: Percona Software Repositories 
site_description: Documentation
site_author: Percona LLC
copyright: Percona LLC, &#169; 2021

site_url: 'https://www.percona.com/doc/percona-repo-config/'
repo_name: /percona/repo-config-docs
repo_url: https://github.com/percona/repo-config-docs
edit_uri: edit/master/docs/

use_directory_urls: false

#Theme for Netlify builds
theme:
  name: material
  logo: _images/percona-logo.png
  favicon: _images/percona-favicon.ico
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: percona-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Theme features

  features:
    - search.highlight
    - navigation.top


#Styling
extra_css:
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  - css/version-select.css
  - css/toctree.css
  - css/percona.css
  - css/table-list.css

extra_javascript:
  - js/version-select.js

markdown_extensions:
  - attr_list
  - toc:
      permalink: True
  - admonition
  - footnotes
  - def_list   # https://michelf.ca/projects/php-markdown/extra/#def-list
  - meta
  - smarty:
        smart_angled_quotes: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
        linenums: false
  

plugins:
  - search
  - git-revision-date
# - bootstrap-tables
  - section-index # Adds links to nodes - comment out when creating PDF
#  - htmlproofer # Uncomment to check links - but extends build time significantly
  - macros:
        include_yaml:
#          - 'variables.yml' # Use in markdown as '{{ VAR }}'


extra:
  version:
    provider: mike


nav:
  - index.md
  - Installation and update:
    - installation-and-update.md
    - installing.md
    - updating.md
  - Usage:
    - usage.md
    - percona-release.md
    - repository-location.md
  - Reference:
    - copyright.md
    - trademark-policy.md